# ==== STAGE 1: Build the Go app ====
FROM golang:1.26.3-alpine AS builder
RUN apk update && apk add --no-cache git curl

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air"]