### Products - V1

### List products
GET http://localhost:8080/api/v1/products?search=khoa%hoc go lang 2c

### Get product by id
GET http://localhost:8080/api/v1/products/2000

### Get product by slug
GET http://localhost:8080/api/v1/products/@khoa#hoc-lap-trinh.html

### Create product
POST http://localhost:8080/api/v1/products

### Update product
PUT http://localhost:8080/api/v1/products/1

### Delete product
DELETE http://localhost:8080/api/v1/products/1
